name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - name: Install dependencies
      run: |
        uv sync --all-extras

    - name: Check code formatting with Black
      run: |
        uv run black --check --diff src/dashboard_lego/ tests/ examples/

    - name: Check import sorting with isort
      run: |
        uv run isort --check-only --diff src/dashboard_lego/ tests/ examples/

    - name: Run linting checks
      run: |
        uv run flake8 src/dashboard_lego/ --max-line-length=88 --extend-ignore=E203,W503,E501

    - name: Run type checking with mypy
      run: |
        uv run mypy src/dashboard_lego/ --ignore-missing-imports --no-strict-optional --explicit-package-bases
      continue-on-error: true

    - name: Run tests with coverage
      run: |
        uv run pytest --cov=dashboard_lego --cov-report=xml --cov-report=term-missing

    - name: Upload coverage to Codecov
      if: matrix.python-version == '3.11'
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
