name: Build and Deploy Documentation

on:
  workflow_run:
    workflows: ["Tests"]  # Зависит от workflow с именем "Tests"
    types: [completed]
    branches: [main]

jobs:
  build-and-deploy-docs:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for peaceiris/actions-gh-pages to push to gh-pages branch

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Получить всю историю для корректной работы с ветками

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv sync --extra docs --extra ml --extra sql

    - name: Build HTML documentation
      run: |
        uv run sphinx-build -b html docs/source docs/build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build
        cname: # Оставьте пустым, если не используете кастомный домен
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
